kind: pipeline
type: docker
name: hello-world

platform:
  os: linux
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: narutowii/docker-hello-world
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
